=== shintaamelia96/Tugas2-Web-Service/barang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="logbarang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jagung"/>
                <xs:element ref="sagu"/>
                <xs:element ref="gandum"/>
                <xs:element ref="singkong"/>
                <xs:element ref="jamur"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jagung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="satuan"/>
                <xs:element ref="harga"/>
                <xs:element ref="jenis_jagung"/>
                <xs:element ref="umur"/>
                <xs:element ref="kualitas"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jenis_jagung" type="xs:NCName"/>
    <xs:element name="sagu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="satuan"/>
                <xs:element ref="harga"/>
                <xs:element ref="umur"/>
                <xs:element ref="kualitas"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="gandum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="satuan"/>
                <xs:element ref="harga"/>
                <xs:element ref="umur"/>
                <xs:element ref="kualitas"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="singkong">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="satuan"/>
                <xs:element ref="harga"/>
                <xs:element ref="umur"/>
                <xs:element ref="kualitas"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jamur">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="satuan"/>
                <xs:element ref="harga"/>
                <xs:element ref="umur"/>
                <xs:element ref="kualitas"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="1"></xs:minLength>
    			<xs:maxLength value="5"></xs:maxLength>
    			<xs:pattern value=".+"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="satuan" type="xs:NCName"/>
    <xs:element name="harga">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">

    			<xs:minInclusive value="1000"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="umur" type="xs:integer"/>
    <xs:element name="kualitas" type="xs:NCName"/>
    <xs:element name="ukuran" type="xs:NCName"/>
    <xs:element name="asal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewil"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tujuan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewil"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:NCName"/>
    <xs:element name="kodewil" type="xs:integer"/>
</xs:schema>

=== shintaamelia96/Tugas2-Web-Service/barang.xml
<?xml version="1.0" encoding="UTF-8"?>
<logbarang xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="barang.xsd">
<jagung>
<kode>M1111</kode>
		<satuan>pc</satuan>
		<harga>1000</harga>
		<jenis_jagung>manis</jenis_jagung>
		<umur>3</umur>
		<kualitas>bagus</kualitas>
		<ukuran>sedang</ukuran>
		<asal>
			<pt>sentosa</pt> 
			<kodewil>10</kodewil>
		</asal>
		 <tujuan>
		 	<pt>luhur</pt> 
		 	<kodewil>123</kodewil>
		 </tujuan>
	</jagung>
<sagu>
	<kode>M112</kode>
	<satuan>pc</satuan>
		<harga>10000</harga>
		<umur>3</umur>
		<kualitas>bagus</kualitas>
		<ukuran>sedang</ukuran>
		<asal>
			<pt>makmur</pt> 
			<kodewil>12</kodewil>
		</asal>
		 <tujuan>
		 	<pt>luhur</pt> 
		 	<kodewil>123</kodewil>
		 </tujuan>
</sagu>
<gandum>
	<kode>M113</kode>
	<satuan>pc</satuan>
		<harga>10000</harga>
		<umur>3</umur>
		<kualitas>bagus</kualitas>
		<ukuran>sedang</ukuran>
		<asal>
			<pt>sentosa</pt> 
			<kodewil>10</kodewil>
		</asal>
		 <tujuan>
		 	<pt>luhur</pt> 
		 	<kodewil>123</kodewil>
		 </tujuan>
</gandum>
<singkong>
	<kode>M114</kode>
	<satuan>pc</satuan>
		<harga>10000</harga>
		<umur>2</umur>
		<kualitas>bagus</kualitas>
		<ukuran>sedang</ukuran>
		<asal>
			<pt>sentosa</pt> 
			<kodewil>10</kodewil>
		</asal>
		 <tujuan>
		 	<pt>luhur</pt> 
		 	<kodewil>123</kodewil>
		 </tujuan>
</singkong>
<jamur>
	<kode>M115</kode>
	<satuan>pc</satuan>
		<harga>10000</harga>
		<umur>1</umur>
		<kualitas>bagus</kualitas>
		<ukuran>sedang</ukuran>
		<asal>
			<pt>sentosa</pt> 
			<kodewil>10</kodewil>
		</asal>
		 <tujuan>
		 	<pt>luhur</pt> 
		 	<kodewil>123</kodewil>
		 </tujuan>
</jamur>
</logbarang>
